#注册中心服务配置
spring:
  application:
    name: dept-eureka

server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/