server:
  port: 9527


spring:
  application:
    name: microservicecloud-Zull-gateways

#注册配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    hostname: zullgateway.com
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

zuul:
  prefix: /lox
  ignored-services: microservicecloud-dept
  routes:
     mydept.serviceId: microservicecloud-dept
     mydept.path: /mydept/**


info:
  app.name: lox-microservicecloud
  company.name: www.lox.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

