#注册中心服务配置
spring:
  application:
    name: dept-eureka

server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
    prefer-ip-address: true
    instance-id:  ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#      ,http://eureka7003.com:7003/eureka/